src/authentication/models.py
from src import db, login_manager
from flask import current_app
from flask_login import UserMixin
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer


@login_manager.user_loader
def load_user(user_id):
	return User.query.get(int(user_id))


class User(db.Model, UserMixin):

	id = db.Column(db.Integer, primary_key=True)
	username = db.Column(db.String(20), unique=True, nullable=False)
	email = db.Column(db.String(120), unique=True, nullable=False)
	image_file = db.Column(db.String(20), nullable=False, default='default.jpg')
	password = db.Column(db.String(60), nullable=False)
	#backref creates a virtual column in Post Model that retrieves all the attributes of User (related by id)
	posts = db.relationship('Post', backref='author', lazy=True)

	#create a timed token
	def get_reset_token(self, expires_sec=1800):
		s = Serializer(current_app.config['SECRET_KEY'], expires_sec)
		return s.dumps({'user_id':self.id}).decode('utf-8')

	@staticmethod
	def verify_reset_token(token):
		s = Serializer(current_app.config['SECRET_KEY'])
		try:
			user_id = s.loads(token)['user_id']
		except:
			return None
		return User.query.get(user_id)

	def __repr__(self):
		return f"User('{self.username}','{self.email}','{self.image_file}')"

src/authentication/forms.py
from src.authentication.models import User
from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_wtf.file import FileField, FileAllowed



# REGISTRATION
class RegistrationForm(FlaskForm):

	username = StringField('Nom d\'utilisateur', validators=[DataRequired(), Length(min=2,max=20)])
	email = StringField('Adresse courriel', validators=[DataRequired(), Email()])
	password = PasswordField('Mot de passe', validators=[DataRequired(), Length(min=6,max=25)])
	confirm_password = PasswordField('Confirmer le mot de passe', validators=[DataRequired(), EqualTo('password')])
	submit = SubmitField('M\'enregistrer')

	def validate_username(self, username):
		user = User.query.filter_by(username=username.data).first()
		if user:
			raise ValidationError('Ce nom d\'utilisateur est déjà pris. Veuillez en choisir un autre.')

	def validate_email(self, email):
		user = User.query.filter_by(email=email.data).first()
		if user:
			raise ValidationError('Cette adresse courriel est déjà prise. Veuillez en choisir une autre.')


# LOGIN
class LoginForm(FlaskForm):

	email = StringField('Adresse courriel', validators=[DataRequired(), Email()])
	password = PasswordField('Mot de passe', validators=[DataRequired()])
	remember = BooleanField('Se rappeler de moi')
	submit = SubmitField('Me connecter')


# UPDATE ACCOUNT
class UpdateAccountForm(FlaskForm):

	username = StringField('Nom d\'utilisateur', validators=[DataRequired(), Length(min=2,max=20)])
	email = StringField('Adresse courriel', validators=[DataRequired(), Email()])
	image = FileField('Modifier l\'image de profil', validators=[FileAllowed(['jpg','png'])])
	submit = SubmitField('Modifier')

	def validate_username(self, username):
		if username.data != current_user.username:
			user = User.query.filter_by(username=username.data).first()
			if user:
				raise ValidationError('Ce nom d\'utilisateur est déjà pris. Veuillez en choisir un autre.')

	def validate_email(self, email):
		if email.data != current_user.email:
			user = User.query.filter_by(email=email.data).first()
			if user:
				raise ValidationError('Cette adresse courriel est déjà prise. Veuillez en choisir une autre.')


# SEND EMAIL
class ResetRequestForm(FlaskForm):

	email = StringField('Adresse e-mail', validators=[DataRequired(), Email()])
	submit = SubmitField('Réinitialiser le mot de passe')

	def validate_email(self, email):
		user = User.query.filter_by(email=email.data).first()
		if user is None:
			raise ValidationError('Cette Adresse courriel n\'est pas associée à un compte. Veuillez vous enregistrer.')


# RESET PASSWORD
class ResetPasswordForm(FlaskForm):

	password = PasswordField('Mot de passe', validators=[DataRequired(), Length(min=6,max=25)])
	confirm_password = PasswordField('Confirmer le mot de passe', validators=[DataRequired(), EqualTo('password')])
	submit = SubmitField('Enregistrer le nouveau mot de passe')

src/authentication/routes.py
from src import db, bcrypt
from src.authentication.models import User
from src.authentication.forms import (RegistrationForm, LoginForm, 
																		UpdateAccountForm, ResetRequestForm, ResetPasswordForm)
from src.authentication.utils import save_image, send_reset_email
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required


authentication = Blueprint('authentication', __name__)



# REGISTER
@authentication.route('/register', methods=['GET','POST'])
def register(): 
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RegistrationForm() 
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(username=form.username.data, email=form.email.data, password=hashed_password)
		db.session.add(user)
		db.session.commit()
		flash('Votre compte a été créé, vous pouvez maintenant vous connecter.', 'success')
		return redirect(url_for('authentication.login'))
	return render_template('authentication/register.html', title='Register', form=form)


# LOGIN
@authentication.route('/login', methods=['GET','POST'])
def login(): 
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.remember.data)
			# http://localhost:5000/login?next=%2Faccount
			next_page = request.args.get('next')
			return redirect(next_page) if next_page else redirect(url_for('main.home'))
		else:
			flash('Erreur de connexion, email ou mot de passe incorrect', 'danger')
	return render_template('authentication/login.html', title='Login', form=form)


# LOGOUT
@authentication.route('/logout')
def logout(): 
	logout_user()
	return redirect(url_for('main.home'))


# ACCOUNT
@authentication.route('/account', methods=['GET','POST'])
@login_required
def account(): 
	form = UpdateAccountForm()
	if form.validate_on_submit():
		if form.image.data:
			image_file = save_image(form.image.data)
			current_user.image_file = image_file
		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash('Votre compte a bien été modifié!', 'success')
		return redirect(url_for('authentication.account')) #to avoid double submit
	elif request.method == 'GET': #to fill form with current infos
		form.username.data = current_user.username
		form.email.data = current_user.email
	image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
	return render_template('authentication/account.html', title='Account', image_file=image_file, form=form)



# SEND EMAIL (TO RESET PASSWORD)
@authentication.route('/reset_password', methods=['GET','POST'])
def reset_request(): 
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = ResetRequestForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		send_reset_email(user)
		flash('Un courriel a été envoyé pour réinitialiser le mot de passe.', 'info')
		return redirect(url_for('authentication.login'))
	return render_template('authentication/reset_request.html', title='Réinitialiser le mot de passe', form=form)


# RESET PASSWORD
@authentication.route('/reset_password/<token>', methods=['GET','POST'])
def reset_password(token): 
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	user = User.verify_reset_token(token)
	if user is None:
		flash('L\'Authentification est invalide ou expirée.', 'warning')
		return redirect(url_for('authentication.reset_request'))
	form = ResetPasswordForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user.password = hashed_password
		db.session.commit()
		flash('Votre mot de passe a été modifié, vous pouvez maintenant vous connecter.', 'success')
		return redirect(url_for('authentication.login'))
	return render_template('authentication/reset_password.html', title='Nouveau mot de passe', form=form)

src/templates/authentication/account.html
{% extends "content_simple.html" %}

{% block form %}
	<form action="" method="post" enctype="multipart/form-data">
	{{ form.hidden_tag() }}
{% endblock form %}


{% block title %}
	<h3>VOTRE COMPTE</h3>
{% endblock title %}


{% block content %}

  <div class="media">
    <img class="rounded-circle account-img" src="{{ image_file }}">
    <div class="media-body">
      <h2 class="account-heading">{{ current_user.username }}</h2>
      <p class="text-secondary">{{ current_user.email }}</p>
    </div>
  </div>

  <div class="content-section my-4">
		<fieldset class="form-group">

			<legend class="border-bottom mb-4">Informations du compte</legend>

			<div class="form-group">
				{{ form.username.label(class="form-control-label") }}
				{% if form.username.errors %}
					{{ form.username(class="form-control form-control-lg is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.username.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% else %}
					{{ form.username(class="form-control form-control-lg") }}
				{% endif %}
			</div>

			<div class="form-group mb-4">
				{{ form.email.label(class="form-control-label") }}
				{% if form.email.errors %}
					{{ form.email(class="form-control form-control-lg is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.email.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% else %}
					{{ form.email(class="form-control form-control-lg") }}
				{% endif %}
			</div>

			<div class="form-group mt-4">
				{{ form.image.label() }}
				{{ form.image(class="form-control-file") }}
				{% if form.image.errors %}
					{% for error in form.image.errors %}
						<span class="text-danger">{{ error }}</span><br>
						{% endfor %}
				{% endif %}
			</div>

		</fieldset>

		<div class="form-group">
			{{ form.submit(class="btn btn-outline-info") }}
		</div>

	</div>

{% endblock content %}


{% block end_form %}
	</form>
{% endblock end_form %}

src/templates/authentication/login.html
{% extends "content_simple.html" %}

{% block form %}
	<form action="" method="post">
	{{ form.hidden_tag() }}
{% endblock form %}


{% block title %}
	<h3>CONNEXION</h3>
{% endblock title %}


{% block content %}

		<fieldset class="form-group">

			<legend class="border-bottom mb-4">Me connecter</legend>

			<div class="form-group">
				{{ form.email.label(class="form-control-label") }}
				{% if form.email.errors %}
					{{ form.email(class="form-control form-control-lg is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.email.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% else %}
					{{ form.email(class="form-control form-control-lg") }}
				{% endif %}
			</div>

			<div class="form-group">
				{{ form.password.label(class="form-control-label") }}				
				{% if form.password.errors %}
					{{ form.password(class="form-control form-control-lg is-invalid") }}
					<div class="invalid-feedback">
						{% for error in form.password.errors %}
						<span>{{ error }}</span>
						{% endfor %}
					</div>
				{% else %}
					{{ form.password(class="form-control form-control-lg") }}
				{% endif %}
			</div>

			<div class="form-check">
				{{ form.remember(class="form-check-input") }}
				{{ form.remember.label(class="form-check-label") }}
			</div>

		</fieldset>

		<div class="form-group mt-4">
			{{ form.submit(class="btn btn-outline-info") }}
			<small class="text-muted mt-3 mr-2 pull-right">
				<a href="{{ url_for('authentication.reset_request') }}">Mot de passe oublié?</a>
			</small>
		</div>

<div class="border-top pt-3">
	<small class="text-muted">
		Vous n'avez pas de compte? <a class="ml-2" href="{{ url_for('authentication.register') }}">Créer un compte</a>
	</small>
</div>

{% endblock content %}


{% block end_form %}
	</form>
{% endblock end_form %}

src/templates/authentication/register.html
{% extends "content_simple.html" %}

{% block form %}
	<form action="" method="post">
	{{ form.hidden_tag() }}
{% endblock form %}


{% block title %}
	<h3>NOUVEAU COMPTE</h3>
{% endblock title %}


{% block content %}

	<fieldset class="form-group">

		<legend class="border-bottom mb-4">Créer mon compte</legend>

		<div class="form-group">
			{{ form.username.label(class="form-control-label") }}

			{% if form.username.errors %}
				{{ form.username(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.username.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
			{% else %}
				{{ form.username(class="form-control form-control-lg") }}
			{% endif %}
		</div>

		<div class="form-group">
			{{ form.email.label(class="form-control-label") }}
			
			{% if form.email.errors %}
				{{ form.email(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.email.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
			{% else %}
				{{ form.email(class="form-control form-control-lg") }}
			{% endif %}
		</div>

		<div class="form-group">
			{{ form.password.label(class="form-control-label") }}
			
			{% if form.password.errors %}
				{{ form.password(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.password.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
			{% else %}
				{{ form.password(class="form-control form-control-lg") }}
			{% endif %}
		</div>
		
		<div class="form-group">
			{{ form.confirm_password.label(class="form-control-label") }}
			
			{% if form.confirm_password.errors %}
				{{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.confirm_password.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
			{% else %}
				{{ form.confirm_password(class="form-control form-control-lg") }}
			{% endif %}
		</div>

		</fieldset>

		<div class="form-group">
			{{ form.submit(class="btn btn-outline-info") }}
		</div>

		<div class="border-top pt-3">
			<small class="text-muted">
				Vous avez déjà un compte? <a class="ml-2" href="{{ url_for('authentication.login') }}">Me connecter</a>
			</small>
		</div>

{% endblock content %}


{% block end_form %}
	</form>
{% endblock end_form %}

src/templates/authentication/reset_password.html
{% extends "content_simple.html" %}

{% block form %}
	<form action="" method="post">
	{{ form.hidden_tag() }}
{% endblock form %}


{% block title %}
	<h3>CRÉATION DU NOUVEAU MOT DE PASSE</h3>
{% endblock title %}


{% block content %}

	<fieldset class="form-group">

		<legend class="border-bottom mb-4">Nouveau mot de passe</legend>

		<div class="form-group">
			{{ form.password.label(class="form-control-label") }}
			{% if form.password.errors %}
				{{ form.password(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.password.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
			{% else %}
				{{ form.password(class="form-control form-control-lg") }}
			{% endif %}
		</div>

		<div class="form-group">
			{{ form.confirm_password.label(class="form-control-label") }}
			{% if form.confirm_password.errors %}
				{{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.confirm_password.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
			{% else %}
				{{ form.confirm_password(class="form-control form-control-lg") }}
			{% endif %}
		</div>

	</fieldset>

	<div class="form-group">
		{{ form.submit(class="btn btn-outline-info") }}
	</div>

{% endblock content %}



{% block end_form %}
	</form>
{% endblock end_form %}

src/templates/authentication/reset_request.html
{% extends "content_simple.html" %}

{% block form %}
	<form action="" method="post">
	{{ form.hidden_tag() }}
{% endblock form %}


{% block title %}
	<h3>RÉINITIALISATION DU MOT DE PASSE</h3>
{% endblock title %}


{% block content %}

	<fieldset class="form-group">

		<legend class="border-bottom mb-4">Réinitialiser le mot de passe</legend>

		<div class="form-group">
			{{ form.email.label(class="form-control-label") }}
			{% if form.email.errors %}
				{{ form.email(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.email.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
			{% else %}
				{{ form.email(class="form-control form-control-lg") }}
			{% endif %}
		</div>

	</fieldset>

	<div class="form-group">
		{{ form.submit(class="btn btn-outline-info") }}
	</div>


{% endblock content %}


{% block end_form %}
	</form>
{% endblock end_form %}